service: nextjs-personwallet

app: nextjs-personwallet # Manter o app para o componente
org: augustodev

provider:
  name: aws
  region: us-east-1
  runtime: nodejs20.x

plugins:
  - "@sls-next/serverless-component"

custom:
  # Opcional: Configurações para o componente, se necessário
  # nextConfigDir: ./
  # nextBuildDir: .next

inputs:
  build:
    cmd: npm run build # Ou yarn build

# Remova as seções functions, resources e s3Sync, pois o componente cuida disso.