service: nextjs-app

app: nextjs-personwallet
org: augustodev

provider:
  name: aws
  region: us-east-2
  runtime: nodejs20.x

plugins:
  - "@sls-next/serverless-component" 
    
  # - "serverless-s3-sync" # Adicionar plugin para sincronizar arquivos para o S3, se necessário

custom:
  nextConfigDir: ./ # Diretório de configuração do Next.js  
  nextBuildDir: .next 
  s3Sync:
    - bucketName: !Ref NextBucket  # Nome do bucket referenciado
      localDir: .next/  # Diretório para sincronizar
      delete: true      # Delete arquivos antigos no bucket
      exclude:
        - .serverless/**  # Excluindo a pasta .serverless
        - .git/**          # Excluindo a pasta .git

# resources:
#   Resources:
#     NextBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         AccessControl: Private
#     CloudFrontOAI:
#       Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
#       Properties:
#         CloudFrontOriginAccessIdentityConfig:
#           Comment: Access Identity for ${AWS::StackName}-bucket
#     NextJSCloudFrontDistribution:
#       Type: AWS::CloudFront::Distribution
#       Properties:
#         DistributionConfig:
#           Enabled: true
#           Origins:
#             - Id: S3-NextJSOrigin
#               DomainName: !GetAtt NextBucket.DomainName
#               S3OriginConfig:
#                 OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
#           DefaultCacheBehavior:
#             AllowedMethods:
#               - GET
#               - HEAD
#             TargetOriginId: S3-NextJSOrigin
#             ViewerProtocolPolicy: redirect-to-https
#             ForwardedValues:
#               QueryString: false
#               Cookies:
#                 Forward: none
#           PriceClass: PriceClass_100
#           ViewerCertificate:
#             CloudFrontDefaultCertificate: true

functions:
  next:
    handler: handler.nextApp
    # package:
    #   individually: true
    #   exclude:
    #     - .git/**
    #     - node_modules/**
    #     - .serverless/**        
    #     - src/tests/**
    events:
      - http:
          path: /{proxy+}
          method: any